name       : libksieve
version    : 18.12.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/libksieve-18.12.0.tar.xz : 776aaff9189c87ad3d239bb26622c302800e65c87102e8bac75f5a5799d78ac3
license    : GPL-2.0-only
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
