name       : libksieve
version    : 20.04.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/libksieve-20.04.0.tar.xz : 26076a3a2f722b9234dd22f739e4d3ff02858b00bca748a079dbd1df10b50df2
homepage   : https://kde.org/
license    : GPL-2.0-only
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
