name       : libksieve
version    : 20.04.1
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/libksieve-20.04.1.tar.xz : 6c80cb0d584fb4d18bb6c31f3589d7929212b90058efcb4b5e8feef2f8b46212
homepage   : https://kde.org/
license    : GPL-2.0-only
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/dic
