name       : libksieve
version    : 17.12.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/libksieve-17.12.3.tar.xz : 631091d0a931d4fdfaf66c5331f10a7b2f8e9edbc1805fb8d5aeb42eb85be1b2
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
