name       : libksieve
version    : 18.08.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/libksieve-18.08.0.tar.xz : eb60dc0fec69e0da4762f8fe7ffb42880e5e762ac49c13dba7b95218b0e0d276
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
