name       : libksieve
version    : 21.12.3
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/libksieve-21.12.3.tar.xz : 6d1faf32d2ae9e90b71590f77acc85fa77d2a4ae38088549257675e30b6329d2
homepage   : https://kde.org/
license    : GPL-2.0-only
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - kwallet-devel
    - libkdepim-devel
    - pimcommon-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
