name       : libksieve
version    : 23.04.1
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/libksieve-23.04.1.tar.xz : c4a6eecfac4a871f7cfbe18d21f8fdfaf6a72568a5385a311a4a0ccb81de21b9
homepage   : https://kde.org/
license    : GPL-2.0-only
component  : programming.library
summary    : Sieve Script Library
description: |
    Sieve Script Library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - knewstuff-devel
    - ktextaddons-devel
    - kwallet-devel
    - libkdepim-devel
    - pimcommon-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
